# Generated by Django 3.0.8 on 2020-07-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(help_text='testing', max_length=130),
        ),
    ]
