# Generated by Django 3.0.8 on 2020-07-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200709_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(help_text='Use - instead of space', max_length=130),
        ),
    ]
